### ISSUE TITLE
Allow to edit closed event process steps

### ISSUE THREAD

**Issue by kazemar** [kalisio/aktnmap#288]
As a user it we be usefull to be able to edit closed steps of an event process : if I made a mistake, or want to correct my answer it's not possible today.

**Comment by claustres** [comment]
Regarding workflows we need to ensure traceability and consistence. The coordinator might have taken action according to the answer of a given user so that changing this answer afterwards could lead to misinformation or error. Similarly, if a user change his state at some point in the workflow this could also change all the following steps if any.

That's the reason why today it's impossible because it implies a lot of potential problems.

**Comment by kazemar** [comment]
Yes your answer is logic. I close this issue.
